
sudo: required

language: java

services:
  - docker

before_install:
  - chmod +x gradlew

script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./gradlew clean buildDockerPush
