
sudo: required

language: java

services:
  - docker

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean war
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t steasdal/hello-world .
  - docker images
  - docker push steasdal/hello-world